name: Build and Deploy Docker Image
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      VITE_APP_SLUG: dashboards_for_lc
      VITE_OPENAPI_URL: https://text-apps-api.darka.io/api/doc?domain=https://dashboards.darka.io
      VITE_APP_NAME: Dashboards
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Build image
        run: |
          touch .env
          echo "VITE_OPENAPI_URL=${{env.VITE_OPENAPI_URL}}" >> .env
          echo "VITE_LC_CLIENT_ID=${{env.VITE_LC_CLIENT_ID}}" >> .env
          echo "VITE_LC_REDIRECT_URI=${{env.VITE_LC_REDIRECT_URI}}" >> .env
          echo "VITE_APP_NAME=${{env.VITE_APP_NAME}}" >> .env
          cat .env
          docker build -t ${{ github.event.repository.name }}:${{ github.sha }} .
      - name: Install docker
        uses: docker/login-action@v3
        with:
          username: darkaio
          password: ${{secrets.REGISTRY_KEY}}
      - name: Tag image

        run: docker tag ${{ github.event.repository.name }}:${{github.sha}}  docker.io/darkaio/${{ github.event.repository.name}}:${{ github.sha }}

      - name: Push image
        run:
          docker push docker.io/darkaio/${{ github.event.repository.name }}:${{
          github.sha }}

      - name: Set output
        run:
          echo "IMAGE_URL=docker.io/darkaio/${{ github.event.repository.name }}:${{
          github.sha }}" >> $GITHUB_ENV

      - name: Deploy LC Twilio client
        uses: caprover/deploy-from-github@v1.1.2
        with:
          server: ${{ secrets.CAPROVER_SERVER }}
          app: ${{ secrets.APP_NAME }}
          token: ${{ secrets.APP_TOKEN }}
          image: ${{ env.IMAGE_URL }}